on:
  release:
    # https://stackoverflow.com/a/61066906
    types: [published]

jobs:
  publishmatrix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/inject.js
